// Builds the docs' design tokens from usaspending.gov's own SCSS.
// 1. Reads the site's src/_scss/core/_variables.scss (sparse clone of the public usaspending-website repo).
// 2. Resolves every $variable to a value and writes tokens/usaspending.json (DTCG format).
// 3. Maps tokens/semantic.json roles to those values for light and dark, and writes app/tokens.css.
// If the site repo can't be fetched, the committed tokens/usaspending.json snapshot is used.
import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const SITE_REPO = 'https://github.com/fedspendingtransparency/usaspending-website';
const VARS = 'src/_scss/core/_variables.scss';
const SNAPSHOT = path.join(ROOT, 'tokens', 'usaspending.json');
const log = (...a) => console.log('[build-tokens]', ...a);

function fetchScss() {
  if (process.env.SITE_SCSS) return { scss: fs.readFileSync(process.env.SITE_SCSS, 'utf8'), sha: null };
  const dest = path.join(ROOT, '.site');
  fs.rmSync(dest, { recursive: true, force: true });
  execSync(`git clone --depth 1 --filter=blob:none --sparse ${SITE_REPO}.git "${dest}"`, { stdio: 'ignore' });
  execSync(`git -C "${dest}" sparse-checkout set --no-cone '/${VARS}'`, { stdio: 'ignore' });
  const sha = execSync(`git -C "${dest}" rev-parse HEAD`).toString().trim();
  return { scss: fs.readFileSync(path.join(dest, VARS), 'utf8'), sha };
}

function parse(scss) {
  const raw = {};
  for (const line of scss.split('\n')) {
    const m = line.replace(/\/\/.*$/, '').match(/^\s*\$([a-z0-9-]+)\s*:\s*([^;]+);/i);
    if (m) raw[m[1]] = m[2].trim();
  }
  const resolve = (v, depth = 0) => {
    if (depth > 10) return v;
    const ref = v.match(/^\$([a-z0-9-]+)$/i);
    if (ref) return raw[ref[1]] !== undefined ? resolve(raw[ref[1]], depth + 1) : v;
    const rem = v.match(/^rem\((\d+(?:\.\d+)?)px\)$/);
    if (rem) return `${Number(rem[1]) / 16}rem`;
    return v;
  };
  const color = {}, fontSize = {}, font = {};
  for (const [k, v] of Object.entries(raw)) {
    const val = resolve(v);
    if (/^#[0-9a-f]{3,8}$/i.test(val) || /^rgba?\(/i.test(val)) color[k] = { $type: 'color', $value: val.toLowerCase(), $extensions: { source: `$${k}: ${v}` } };
    else if (/^font-size-\d+$/.test(k)) fontSize[k] = { $type: 'dimension', $value: val };
  }
  font.sans = { $type: 'fontFamily', $value: "'Source Sans 3', 'Source Sans Pro', 'Helvetica Neue', Arial, sans-serif", $extensions: { source: `$font-sans: ${raw['font-sans'] || ''}` } };
  font.mono = { $type: 'fontFamily', $value: "'Source Code Pro', ui-monospace, Menlo, monospace", $extensions: { note: 'Monospace sibling of Source Sans; the site uses the browser default monospace.' } };
  color.white = color.white || { $type: 'color', $value: '#ffffff' };
  return { color, fontSize, font };
}

function build() {
  let tokens;
  try {
    const { scss, sha } = fetchScss();
    tokens = { $description: `Generated from ${SITE_REPO}/blob/${sha || 'main'}/${VARS}. Do not edit by hand.`, source: { repo: SITE_REPO, file: VARS, sha }, ...parse(scss) };
    fs.writeFileSync(SNAPSHOT, JSON.stringify(tokens, null, 2));
    log(`${Object.keys(tokens.color).length} colors, ${Object.keys(tokens.fontSize).length} type sizes from the site's SCSS`);
  } catch (err) {
    if (!fs.existsSync(SNAPSHOT)) throw err;
    tokens = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
    log('Could not fetch the site SCSS, using the committed snapshot:', err.message);
  }
  const semantic = JSON.parse(fs.readFileSync(path.join(ROOT, 'tokens', 'semantic.json'), 'utf8'));
  const val = (name) => {
    const t = tokens.color[name];
    if (!t) throw new Error(`Semantic token refers to $${name}, which the site's SCSS doesn't define`);
    return t.$value;
  };
  const block = (theme) => Object.entries(semantic[theme]).map(([k, v]) => `  --c-${k}: ${val(v)};`).join('\n');
  const sizes = Object.entries(tokens.fontSize).map(([k, v]) => `  --${k}: ${v.$value};`).join('\n');
  const css = `/* Generated by scripts/build-tokens.mjs from usaspending.gov's _variables.scss. Do not edit by hand. */
:root {
${sizes}
  --font-sans: ${tokens.font.sans.$value};
  --font-mono: ${tokens.font.mono.$value};
${block('light')}
  color-scheme: light;
}
:root[data-theme='dark'] {
${block('dark')}
  color-scheme: dark;
}
`;
  fs.writeFileSync(path.join(ROOT, 'app', 'tokens.css'), css);
  log(`app/tokens.css written with ${Object.keys(semantic.light).length} roles for light and dark`);
}

build();
