// Writes app/tokens.css from tokens/tokens.json. Only the semantic layer becomes CSS variables.
import fs from 'node:fs';
import path from 'node:path';
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const t = JSON.parse(fs.readFileSync(path.join(ROOT, 'tokens', 'tokens.json'), 'utf8'));
const get = (ref) => ref.split('.').reduce((o, k) => o?.[k], t);
const resolve = (v) => (typeof v === 'string' ? v.replace(/\{([^}]+)\}/g, (_, r) => resolve(get(r)?.$value ?? '')) : v);
const lines = [];
const walk = (node, prefix) => {
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith('$')) continue;
    if (v && typeof v === 'object' && '$value' in v) lines.push(`  --${prefix}-${k}: ${resolve(v.$value)};`);
    else if (v && typeof v === 'object') walk(v, `${prefix}-${k}`.replace(/^-/, ''));
  }
};
for (const [group, node] of Object.entries(t.semantic)) walk(node, group);
const css = `/* Generated by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit by hand. */\n:root {\n${lines.join('\n')}\n}\n`;
fs.writeFileSync(path.join(ROOT, 'app', 'tokens.css'), css);
console.log(`[build-tokens] ${lines.length} tokens -> app/tokens.css`);
